src/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index_page, name='home'),    
    path('export/', views.export, name='export'),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace="core")),    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/models.py
from django.db import models

# Create your models here.
class Job(models.Model):
   customer_name = models.CharField(max_length=100)
   item_name = models.CharField(max_length=100)
   price = models.PositiveIntegerField()
   quantity = models.PositiveIntegerField()
   total_price = models.PositiveIntegerField(blank=True)   
   date = models.DateTimeField(auto_now_add=True)
   def save(self, *args, **kwargs):
      self.total_price = self.price * self.quantity
      super().save(*args, **kwargs)

   def __str__(self):
      return " {} - {} items for {}".format(self.customer_name, self.item_name,  self.total_price)

   

src/core/forms.py
from .models import Job
from django import forms

class JobForm(forms.ModelForm): 
   class Meta: 
      model = Job 
      fields = ['customer_name', 'item_name', 'quantity', 'price']
      widgets = {'customer_name':forms.TextInput(attrs={'class':'form-control'}), 
               'item_name':forms.TextInput(attrs={'class':'form-control'}),
               'quantity':forms.TextInput(attrs={'class':'form-control'}),
               'price':forms.TextInput(attrs={'class':'form-control'}),
               }

src/core/views.py
import csv
from django.http import HttpResponse
from django.shortcuts import render
from .models import Job
from .forms import JobForm
# Create your views here.

def index_page(request):
   if request.method == 'POST':
      fm = JobForm(request.POST)
      if fm.is_valid():
         fm.save()         
         fm = JobForm()
   else:
      fm = JobForm()

   # qs = Job.objects.all()
   qs = Job.objects.order_by('-id')
   context = {
      'jobs':qs,
      'form':fm,
   }
   return render(request, 'core/index.html', context)

def export(request):
   response = HttpResponse(content_type='text/csv')

   writer = csv.writer(response)
   writer.writerow([ 'Date', 'Customer Name', 'Item Name', 'Quantity', 'Price', 'Total Price'])

   for item in Job.objects.all().values_list( 'date', 'customer_name', 'item_name', 'quantity', 'price', 'total_price'):
      writer.writerow(item)

   response['Content-Disposition'] = 'attachment; filename="order.csv"'

   return response

src/core/templates/core/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<h1 class="text-primary">Job Order</h1><hr>
<div class="row">      
   <div class="col-sm-4 p-5">      
      <div class="card">
         <div class="card-header">
            <h4>Add order</h4>
         </div>
         <div class="card-body">
            <form action="" method="POST">
               {% csrf_token %}
               {{form.as_p}}
               <input type="submit" class="btn btn-success btn-sm" value="Add">
            </form>
         </div>
      </div>
      
      
   </div>
   <div class="col-sm-8 p-5">
      <div class="card">
         <div class="card-header">
            <h4>Order Detail</h4>
         </div>
         <div class="card-body">
            <table class="table table-hover">
               <thead>
                  <tr>
                     <th>#</th>
                     <th>Date</th>
                     <th>Customer Name</th>
                     <th>Item Name</th>
                     <th>Quantity</th>
                     <th>Price</th>
                     <th>Total Price</th>
                  </tr>
               </thead>
               <tbody>
                  {% for d in jobs %}
                     <tr>
                        <td>{{d.id}}</td>
                        <td>{{d.date}}</td>
                        <td>{{d.customer_name}}</td>            
                        <td>{{d.item_name}}</td>
                        <td>{{d.quantity}}</td>
                        <td>{{d.price}}</td>            
                        <td>{{d.total_price}}</td>
                     </tr>
                  {% endfor %}
               </tbody>
            </table>            
         </div>
      </div>   <br>  
      <a href="{% url 'core:export' %}" class="btn btn-success btn-sm">Save as csv</a>
   </div>
</div>

{% endblock content %}

src/core/templates/core/invoice.html
{% extends 'base.html' %}

{% block title %}Order Detail{% endblock title %}

{% block content %}
<h1 class="text-primary">Job Invoice</h1><hr>


<a href="" class="btn btn-success btn-sm">Save as pdf</a>
   
{% endblock content %}

src/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <div class="container my-5">      
      {% block content %}{% endblock content %} 
    </div>

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

   
  </body>
</html>